#
FROM python:3.10

#
WORKDIR /app

#
COPY ./requirements.txt /app/requirements.txt

#
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

#
COPY ./set_money_consumer.py /app/set_money_consumer.py
COPY ./config.py /app/config.py
COPY ./.env /app/.env
COPY ./infrastructure/event_managers /app/infrastructure/event_managers
COPY ./infrastructure/logging.py /app/infrastructure/logging.py

#
CMD ["python", "set_money_consumer.py"]